// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StylishWebsiteBE.Data;
using StylishWebsiteBE.Domain.ValueObjects;

#nullable disable

namespace StylishWebsiteBE.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240301173626_UpdateOptionValue")]
    partial class UpdateOptionValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Options.OptionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductReadModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "Name", "IsDeleted" });

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Id", "IsDeleted" });

                    b.HasIndex("ProductReadModelId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Options.OptionValueReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductVariantReadModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Updating");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "OptionId", "Value", "IsDeleted" });

                    b.HasIndex("OptionId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OptionId"), new[] { "Id", "Value", "IsDeleted" });

                    b.HasIndex("ProductVariantReadModelId");

                    b.HasIndex("Value");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Value"), new[] { "Id", "OptionId", "IsDeleted" });

                    b.ToTable("OptionValues");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductOptionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "OptionId", "ProductId" });

                    b.HasIndex("OptionId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OptionId"), new[] { "Id", "ProductId" });

                    b.HasIndex("ProductId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId"), new[] { "Id", "OptionId" });

                    b.ToTable("ProductOptions");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "Name", "Description", "Category", "Brand", "IsDeleted", "CreatedBy", "CreatedTime", "ModifiedBy", "ModifiedTime", "DeletedBy", "DeletedTime" });

                    b.HasIndex("Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Id", "Description", "Category", "Brand", "IsDeleted", "CreatedBy", "CreatedTime", "ModifiedBy", "ModifiedTime", "DeletedBy", "DeletedTime" });

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductVariantReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ICollection<ImageValueObject>>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ImportPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<double>("Sale")
                        .HasColumnType("double precision");

                    b.Property<string>("SkuId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "SkuId", "ProductId", "ImportPrice", "Price", "Quantity", "IsDeleted" });

                    b.HasIndex("Price");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Price"), new[] { "Id", "ProductId", "ImportPrice", "SkuId", "Quantity", "IsDeleted" });

                    b.HasIndex("ProductId");

                    b.HasIndex("SkuId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("SkuId"), new[] { "Id", "ProductId", "ImportPrice", "Price", "Quantity", "IsDeleted" });

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.VariantValueReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "OptionId", "ProductId", "ProductVariantId", "ValueId" });

                    b.HasIndex("ProductId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId"), new[] { "OptionId", "Id", "ProductVariantId", "ValueId" });

                    b.HasIndex("ProductVariantId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductVariantId"), new[] { "OptionId", "Id", "ProductId", "ValueId" });

                    b.ToTable("VariantValues");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Options.OptionReadModel", b =>
                {
                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductReadModel", null)
                        .WithMany("Options")
                        .HasForeignKey("ProductReadModelId");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Options.OptionValueReadModel", b =>
                {
                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Options.OptionReadModel", "Option")
                        .WithMany("OptionValues")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductVariantReadModel", null)
                        .WithMany("OptionValues")
                        .HasForeignKey("ProductVariantReadModelId");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductOptionReadModel", b =>
                {
                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Options.OptionReadModel", "Option")
                        .WithMany("ProductOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductReadModel", "Product")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductVariantReadModel", b =>
                {
                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductReadModel", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.VariantValueReadModel", b =>
                {
                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Options.OptionReadModel", "Options")
                        .WithMany("VariantValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Options.OptionValueReadModel", "OptionValue")
                        .WithMany("VariantValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductOptionReadModel", "ProductOptions")
                        .WithMany("VariantValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductReadModel", "Products")
                        .WithMany("VariantValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StylishWebsiteBE.Domain.ReadModels.Products.ProductVariantReadModel", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionValue");

                    b.Navigation("Options");

                    b.Navigation("ProductOptions");

                    b.Navigation("ProductVariant");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Options.OptionReadModel", b =>
                {
                    b.Navigation("OptionValues");

                    b.Navigation("ProductOptions");

                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Options.OptionValueReadModel", b =>
                {
                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductOptionReadModel", b =>
                {
                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductReadModel", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("ProductOptions");

                    b.Navigation("ProductVariants");

                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("StylishWebsiteBE.Domain.ReadModels.Products.ProductVariantReadModel", b =>
                {
                    b.Navigation("OptionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
